
const KEY='mi_garaje_public_demo_v1',SEED={"schemaVersion":3,"vehicles":[{"id":"demo1","alias":"Coupé Azul","brand":"Aurelia","model":"GT 300","type":"Coche","status":"Activo","plate":"1234 DEM","vin":"","purchase":"15/03/2023","firstRegistration":"15/03/2023","km":18470,"mileageUpdated":"09/09/2026","insurance":{"company":"Demo Seguros","policy":"DEMO-001","holder":"Demo","coverage":"Todo riesgo","start":"15/03/2023","renewal":"15/03/2027","price":520,"bank":""}},{"id":"demo2","alias":"Trail 900","brand":"Nord","model":"Adventure 900","type":"Moto","status":"Activo","plate":"5678 DEM","vin":"","purchase":"20/06/2024","firstRegistration":"20/06/2024","km":6320,"mileageUpdated":"09/09/2026","insurance":{"company":"Demo Seguros","policy":"DEMO-002","holder":"Demo","coverage":"Todo riesgo","start":"20/06/2024","renewal":"20/06/2027","price":210,"bank":""}},{"id":"demo3","alias":"Bici Carbon","brand":"Kron","model":"XC Pro","type":"Bici","status":"Activo","plate":"","vin":"","purchase":"","firstRegistration":"","km":2150,"mileageUpdated":"09/09/2026","insurance":null}],"workshop":[{"id":"dw1","vehicle":"demo1","date":"12/05/2026","km":15000,"place":"Taller Demo","description":"Revisión: aceite, filtros y líquido de frenos","cost":315,"kind":"Revisión"},{"id":"dw2","vehicle":"demo2","date":"18/07/2026","km":5100,"place":"Moto Demo","description":"Revisión general y ajuste de cadena","cost":145,"kind":"Mantenimiento"},{"id":"dw3","vehicle":"demo3","date":"03/08/2026","km":1900,"place":"Bike Demo","description":"Pastillas de freno y ajuste de cambio","cost":68,"kind":"Mantenimiento"}],"tires":[{"id":"dt1","vehicle":"demo1","date":"10/01/2026","km":12000,"place":"Neumáticos Demo","description":"Neumáticos deportivos","cost":720,"position":"4 ruedas"},{"id":"dt2","vehicle":"demo2","date":"18/07/2026","km":5100,"place":"Moto Demo","description":"Neumático trail","cost":185,"position":"Trasero"},{"id":"dt3","vehicle":"demo3","date":"03/08/2026","km":1900,"place":"Bike Demo","description":"Cubierta XC","cost":55,"position":"Trasera"}],"itv":[],"taxes":[],"other":[{"id":"do1","vehicle":"demo2","date":"05/07/2026","km":4900,"place":"Accesorios Demo","description":"Maletas laterales","cost":890,"kind":"Accesorios"}]};let db;try{db=JSON.parse(localStorage.getItem(KEY))||SEED}catch(e){db=SEED}
function isGasGas(v){return (v.plate||'').replace(/\s/g,'').toUpperCase()==='B-9378-SS'||((v.brand||'').toLowerCase().includes('gas gas')&&(v.model||'').toLowerCase().includes('250'))}
function migrateV66(){let changed=false;(db.vehicles||[]).forEach(v=>{if(v.type!=='Bici'&&!isGasGas(v)&&v.purchase){let f=pd(v.firstRegistration);if(!f||f.getFullYear()<1950){v.firstRegistration=v.purchase;changed=true}}});if(changed)save()}
setTimeout(migrateV66,0);
db.vehicles.forEach(v=>{v.mileageHistory=v.mileageHistory||[];if(v.km && !v.mileageUpdated){v.mileageUpdated='';}});
let state={page:'garage',filter:'Moto',vid:null,module:null};const app=()=>document.getElementById('app');const esc=x=>String(x??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch(e){alert('No se ha podido guardar este cambio en el iPhone. El almacenamiento puede estar lleno. Exporta una copia de seguridad antes de continuar.');return false}};
function pd(s){if(!s||s.startsWith('Año'))return null;let a=s.split('/').map(Number);return a.length===3?new Date(a[2],a[1]-1,a[0]):null}function fd(d){return d?String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear():''}function dy(d){return Math.ceil((d-new Date())/86400000)}function ay(d,n){let x=new Date(d);x.setFullYear(x.getFullYear()+n);return x}function V(){return db.vehicles.find(x=>x.id===state.vid)}function latest(a,id){return a.filter(x=>x.vehicle===id&&pd(x.date)).sort((x,y)=>pd(y.date)-pd(x.date))[0]}
function itvDue(v){if(v.type==='Bici')return null;let l=latest(db.itv,v.id);if(l?.nextDate)return pd(l.nextDate);let f=pd(v.firstRegistration);return f?ay(f,4):null}function stat(d){if(!d)return ['Pendiente','bad'];let n=dy(d);return n<0?['Vencida','bad']:n<=30?[n+' días','warn']:[n+' días','good']}
function bottom(){return `<div class=copyright>© Cem 2026</div><div class=bottom>${[['garage','⌂','Garaje'],['agenda','▣','Agenda'],['spend','▥','Gastos'],['more','•••','Más']].map(n=>`<div class="nav ${state.page===n[0]?'on':''}" onclick="go('${n[0]}')"><b>${n[1]}</b>${n[2]}</div>`).join('')}</div>`}function go(p){state.page=p;render()}
function garage(){let vs=db.vehicles.filter(v=>state.filter==='Histórico'?v.status==='Histórico':v.type===state.filter&&v.status==='Activo');vs.sort((a,b)=>{let A=pd(a.purchase),B=pd(b.purchase);return (B?B.getTime():-Infinity)-(A?A.getTime():-Infinity)||String(a.alias||'').localeCompare(String(b.alias||''),'es')});app().innerHTML=`<div class=top><div class=brandrow><div><div class=brand>◉ Mi Garaje</div><div class=sub>Tus vehículos, siempre al día</div></div><button class=plus>+</button></div><div class=chips>${['Moto','Coche','Bici','Histórico'].map(x=>`<button class="chip ${state.filter===x?'on':''}" onclick="state.filter='${x}';render()">${x==='Coche'?'Coches':x==='Moto'?'Motos':x==='Bici'?'Bicis':x}</button>`).join('')}</div></div><main>${vs.map(v=>vehicleCard(v)).join('')}</main>${bottom()}`}
function vehicleCard(v){let i=stat(itvDue(v)),sd=v.insurance?stat(pd(v.insurance.renewal)):null,t=latest(db.tires,v.id),tk=t&&v.km&&t.km?Math.max(0,+v.km-+t.km):null;let ms=v.type==='Bici'?[['🔧','Mantenimiento',latest(db.workshop,v.id)?.date||'Sin datos'],['◉','Neumáticos',tk!=null?tk.toLocaleString('es-ES')+' km':'Sin km'],['','', '']]:[['▣','ITV',i[0]],['⬟','Seguro',sd?sd[0]:'Pendiente'],['◉','Neumáticos',tk!=null?tk.toLocaleString('es-ES')+' km':'Sin km']];return `<div class=vehicle onclick="openV('${v.id}')"><div class=vpic>${v.photo?`<img src="${v.photo}" style="width:100%;height:100%;object-fit:cover">`:v.type==='Bici'?'🚲':v.type==='Moto'?'🏍️':'🚙'}<span class=type>${v.type==='Bici'?'Bicicleta':v.type}</span><div class=vtitle><strong>${esc(v.alias)}</strong>${v.type!=='Bici'?`<span class="plate editable" onclick="event.stopPropagation();state.vid='${v.id}';state.page='vehicle';render();setTimeout(()=>editVehicleField('plate'),0)">${v.plate?esc(v.plate):'＋ Añadir matrícula'}</span>`:''}</div></div><div class=metrics>${ms.map((m,j)=>m[0]?`<div class=metric><span>${m[0]} ${m[1]}</span><b class="${j<2&&v.type!=='Bici'?(j===0?i[1]:sd?.[1]||'bad'):''}">${esc(m[2])}</b></div>`:'<div></div>').join('')}</div></div>`}
function openV(id){state.vid=id;state.page='vehicle';render()}
function todayES(){let d=new Date();return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}
function updateMileage(){let v=V(),n=prompt('Kilometraje actual:',v.km||'');if(n===null||String(n).trim()==='')return;n=Number(String(n).replace(/\./g,'').replace(',','.'));if(!Number.isFinite(n)||n<0){alert('Introduce un kilometraje válido.');return}let d=prompt('Fecha de lectura:',todayES());if(!d)return;v.mileageHistory=v.mileageHistory||[];if(v.km)v.mileageHistory.push({km:v.km,date:v.mileageUpdated||''});v.km=n;v.mileageUpdated=d;save();render()}
function editVehicleField(field){let v=V(),label='',old='',val=null;if(field==='km'){updateMileage();return}if(field==='plate'){if(v.type==='Bici')return;label='Matrícula';old=v.plate||''}else if(field==='firstRegistration'){label='Fecha de primera matriculación (dd/mm/aaaa)';old=v.firstRegistration||''}else return;val=prompt(label+':',old);if(val===null)return;v[field]=String(val).trim();save();render()}
function editPending(vehicleId,field){state.vid=vehicleId;if(field==='insurance'){state.page='insurance';render();return}if(field==='tires'){state.page='tires';render();return}state.page='vehicle';render();setTimeout(()=>editVehicleField(field),0)}
function vehicle(){let v=V(),i=stat(itvDue(v)),sd=v.insurance?stat(pd(v.insurance.renewal)):null,t=latest(db.tires,v.id),tk=t&&v.km&&t.km?Math.max(0,+v.km-+t.km):null;let mods=v.type==='Bici'?[['workshop','🔧','Taller'],['tires','◉','Neumáticos'],['other','▤','Otros']]:[['workshop','🔧','Taller'],['tires','◉','Neumáticos'],['insurance','⬟','Seguro'],['itv','▣','ITV'],['taxes','€','Impuestos'],['other','▥','Gastos']];app().innerHTML=`<div class=top><button class=back onclick="go('garage')">‹ Mi Garaje</button></div><main><div class=hero><div class=heroimg>${v.photo?`<img src="${v.photo}">`:v.type==='Bici'?'🚲':v.type==='Moto'?'🏍️':'🚙'}<div class=herotxt><h1>${esc(v.alias)}</h1>${v.plate?`<span class=plate>${esc(v.plate)}</span>`:''}</div><button class=photobtn onclick=pickPhoto()>＋ Foto</button><input id=photo type=file accept="image/*" hidden onchange=setPhoto(this.files[0])></div><div class=dashboard>${v.type!=='Bici'?`<div class="dash ringdash" onclick="${'${!v.firstRegistration?"editVehicleField(\'firstRegistration\')":"openM(\'itv\')"}'}"><div class="progressring cyan"><span>ITV</span></div><b>${i[0]}</b><small>${itvDue(v)?'Vence '+fd(itvDue(v)):'Completar matrícula'}</small></div><div class="dash ringdash" onclick="openM('insurance')"><div class="progressring mint"><span>Seguro</span></div><b>${sd?sd[0]:'Pendiente'}</b><small>${v.insurance?.renewal||'Completar datos'}</small></div>`:''}<div class="dash blue" onclick="openM('tires')">◉ Neumáticos<b>${tk!=null?tk.toLocaleString('es-ES')+' km':'—'}</b><small>${t?'Montados: '+t.date:'Sin datos'}</small></div><div class="dash mileage" onclick=updateMileage()>◴ Kilometraje<b>${v.km?Number(v.km).toLocaleString('es-ES')+' km':'—'}</b><small>${v.mileageUpdated?'Actualizado '+esc(v.mileageUpdated):'Fecha no registrada'} · <u>Actualizar</u></small></div></div><div class=modules>${mods.map(m=>`<div class=mod onclick="openM('${m[0]}')"><div class=ico>${m[1]}</div>${m[2]}</div>`).join('')}</div></div><div class=section>Información del vehículo</div><div class=card>${(v.type==='Bici'?[['Marca',v.brand],['Modelo',v.model],['Tipo',v.type],['Fecha de compra',v.purchase||'—'],['Bastidor',v.vin||'—']]:[['Marca',v.brand],['Modelo',v.model],['Tipo',v.type],['Matrícula',v.plate||'—'],['Fecha de compra',v.purchase||'—'],['Primera matriculación',v.firstRegistration||'—'],['Bastidor',v.vin||'—']]).map(r=>`<div class=row><span class=muted>${r[0]}</span><b>${esc(r[1])}</b></div>`).join('')}</div></main>${bottom()}`}
function pickPhoto(){document.getElementById('photo').click()}function setPhoto(f){if(!f)return;let r=new FileReader();r.onload=()=>{let img=new Image();img.onload=()=>{let max=1200,w=img.width,h=img.height,scale=Math.min(1,max/Math.max(w,h)),c=document.createElement('canvas');c.width=Math.round(w*scale);c.height=Math.round(h*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);let previous=V().photo;V().photo=c.toDataURL('image/jpeg',.82);if(!save()){V().photo=previous;return}render()};img.onerror=()=>alert('No se ha podido leer esa foto.');img.src=r.result};r.readAsDataURL(f)}
function openM(m){state.module=m;state.page=m;render()}function moduleHead(title){return `<div class=top><button class=back onclick="state.page='vehicle';render()">‹ ${esc(V().alias)}</button><div class=head><h1>${title}</h1><button class=add onclick=addRecord()>＋ Añadir</button></div></div>`}
function recurringMaintenanceRecords(vehicleId){
  const plans={glc:{amount:70,day:17,label:'Cuota mensual mantenimiento Mercedes'},smart:{amount:38.01,day:17,label:'Cuota mensual mantenimiento Smart'}};
  const plan=plans[vehicleId];if(!plan)return [];
  const now=new Date(),year=now.getFullYear(),rows=[];
  for(let month=0;month<12;month++){let due=new Date(year,month,plan.day);if(due>now)break;rows.push({id:`recmaint_${vehicleId}_${year}_${month+1}`,vehicle:vehicleId,date:fd(due),km:'',place:'Plan de mantenimiento',description:plan.label,cost:plan.amount,kind:'Cuota mantenimiento',recurring:true})}
  return rows
}
function workshop(){let rows=[...db.workshop.filter(x=>x.vehicle===state.vid),...recurringMaintenanceRecords(state.vid)].sort((a,b)=>(pd(b.date)||0)-(pd(a.date)||0));app().innerHTML=moduleHead('🔧 Taller')+`<main><input class=search placeholder="Buscar frenos, batería, aceite..." oninput="filterEvents(this.value)"><div id=events class=timeline>${rows.map(eventHtml).join('')||'<div class=card>Sin intervenciones.</div>'}</div></main>${bottom()}`}
function eventHtml(x){return `<div class=event data-search="${esc((x.description+' '+x.kind+' '+x.place).toLowerCase())}"><div class=date>${esc(x.date)} ${x.km?`<span class=muted>· ${Number(x.km).toLocaleString('es-ES')} km</span>`:''}</div><div class=eventcard><span class=tag>${esc(x.kind)}</span>${x.cost!==''?`<span class=cost>${Number(x.cost).toLocaleString('es-ES',{minimumFractionDigits:2})} €</span>`:''}<b style="display:block;margin-top:9px">${esc(x.place)}</b><ul class=ops>${x.description.split(';').map(o=>`<li>${esc(o.trim())}</li>`).join('')}</ul></div></div>`}function filterEvents(q){document.querySelectorAll('.event').forEach(x=>x.style.display=x.dataset.search.includes(q.toLowerCase())?'':'none')}
function tires(){let rows=db.tires.filter(x=>x.vehicle===state.vid).sort((a,b)=>(pd(b.date)||0)-(pd(a.date)||0)),v=V();app().innerHTML=moduleHead('◉ Neumáticos')+`<main>${rows.map((x,j)=>{let age=x.km&&v.km?Math.max(0,+v.km-+x.km):null;return `<div class=card><span class=tag>${j===0?'Montados / último registro':'Histórico'}</span><span class=cost>${Number(x.cost||0).toLocaleString('es-ES',{minimumFractionDigits:2})} €</span><h3>${esc(x.description)}</h3><div class=row><span class=muted>Fecha</span><b>${esc(x.date)}</b></div><div class=row><span class=muted>Km al montar</span><b>${x.km?Number(x.km).toLocaleString('es-ES')+' km':'—'}</b></div><div class=row><span class=muted>Uso desde entonces</span><b>${age!=null?age.toLocaleString('es-ES')+' km':'—'}</b></div><div class=row><span class=muted>Taller</span><b>${esc(x.place)}</b></div><div class=row><span class=muted>Posición</span><b>${esc(x.position||'—')}</b></div></div>`}).join('')||'<div class=card>Sin neumáticos registrados.</div>'}</main>${bottom()}`}
function insurance(){
  let policies=(db.insurancePolicies||[]).filter(x=>x.vehicle===state.vid).sort((a,b)=>(b.active?1:0)-(a.active?1:0)||dateValue(b.start)-dateValue(a.start));
  let pays=(db.insuranceHistory||[]).filter(x=>x.vehicle===state.vid).sort((a,b)=>dateValue(b.date)-dateValue(a.date));
  let years={};pays.forEach(x=>{let y=(x.date||'').slice(-4);if(!/^\d{4}$/.test(y))y='Sin año';(years[y]=years[y]||[]).push(x)});
  app().innerHTML=moduleHead('⬟ Seguro','Añadir póliza')+`<main>
  <div class=section>Pólizas</div>
  ${policies.map(p=>`<div class=card><h3>${esc(p.company||'Compañía')} ${p.active?'<span class=ok>ACTUAL</span>':''}</h3>${[['Póliza',p.policy],['Tomador',p.holder],['Conductor adicional',p.additional],['Cobertura',p.coverage],['Inicio',p.start],['Fin',p.end],['Banco',p.bank]].map(r=>`<div class=row><span class=muted>${r[0]}</span><b>${esc(r[1]||'—')}</b></div>`).join('')}<div class=recordactions><button onclick="editPolicy('${p.id}')">Editar</button><button class=dangerbtn onclick="deleteRecord('insurancePolicies','${p.id}')">Eliminar</button></div></div>`).join('')||'<div class=card>Sin pólizas registradas.</div>'}
  <div class="section sectionaction"><span>Histórico de primas</span><button class=add onclick=addInsurancePayment()>＋ Añadir cuota</button></div>
  ${Object.keys(years).sort((a,b)=>b.localeCompare(a)).map(y=>{let arr=years[y],tot=arr.reduce((n,x)=>n+(Number(x.cost)||0),0);return `<div class=card><h3>${esc(y)} · Total anual ${money(tot)}</h3>${arr.map(x=>`<div class=row><span>${esc(x.date||'Sin fecha')}</span><b>${money(x.cost)}</b></div><div class=recordactions><button onclick="editInsurancePayment('${x.id}')">Editar</button><button class=dangerbtn onclick="deleteRecord('insuranceHistory','${x.id}')">Eliminar</button></div>`).join('')}</div>`}).join('')||'<div class=card>Sin primas anteriores registradas.</div>'}</main>${bottom()}`
}
function editInsurance(){editPolicy(null)}
function editPolicy(id){
  let x=id?(db.insurancePolicies||[]).find(r=>r.id===id):null;
  let company=prompt('Compañía:',x?.company||'');if(company===null)return;
  let policy=prompt('Póliza:',x?.policy||'');if(policy===null)return;
  let holder=prompt('Tomador:',x?.holder||'');if(holder===null)return;
  let additional=prompt('Conductor adicional:',x?.additional||'');if(additional===null)return;
  let coverage=prompt('Cobertura:',x?.coverage||'');if(coverage===null)return;
  let start=promptDate('Fecha de inicio',x?.start||'');if(start===null||start===undefined)return;
  let end=promptDate('Fecha de fin (vacío si vigente)',x?.end||'');if(end===null||end===undefined)return;
  let bank=prompt('Banco:',x?.bank||'');if(bank===null)return;
  let active=confirm('¿Es la póliza actual/vigente?');
  let rec={id:x?.id||uid('pol'),vehicle:state.vid,company:company.trim(),policy:policy.trim(),holder:holder.trim(),additional:additional.trim(),coverage:coverage.trim(),start,end,bank:bank.trim(),active};
  db.insurancePolicies=db.insurancePolicies||[];if(active)db.insurancePolicies.filter(q=>q.vehicle===state.vid).forEach(q=>q.active=false);
  if(x)Object.assign(x,rec);else db.insurancePolicies.push(rec);save();render()
}
function addInsurancePayment(){editInsurancePayment(null)}
function editInsurancePayment(id){
  let x=id?(db.insuranceHistory||[]).find(r=>r.id===id):null;
  let date=promptDate('Fecha de la cuota/pago',x?.date||todayES());if(date===null||date===undefined||!date)return;
  let cost=promptNumber('Importe de la cuota (€)',x?.cost??'');if(cost===null||cost===undefined||cost==='')return;
  let rec={id:x?.id||uid('ins'),vehicle:state.vid,date,cost};
  db.insuranceHistory=db.insuranceHistory||[];if(x)Object.assign(x,rec);else db.insuranceHistory.push(rec);save();render()
}

function itv(){let v=V(),d=itvDue(v),st=stat(d),rows=(db.itv||[]).filter(x=>x.vehicle===state.vid).sort((a,b)=>(pd(b.date)||0)-(pd(a.date)||0));app().innerHTML=moduleHead('▣ ITV')+`<main><div class=card><div class=muted>Próximo vencimiento</div><div style="font-size:34px;font-weight:850;margin:5px 0">${esc(st[0])}</div><b>${d?fd(d):'Falta primera matriculación o ITV registrada'}</b></div><div class=section>Historial ITV</div>${rows.map(x=>`<div class=card><h3>${esc(x.date||'Sin fecha')}</h3><div class=row><span class=muted>Resultado</span><b>${esc(x.result||'—')}</b></div><div class=row><span class=muted>Centro ITV</span><b>${esc(x.center||'—')}</b></div><div class=row><span class=muted>Próximo vencimiento</span><b>${esc(x.nextDate||'—')}</b></div><div class=row><span class=muted>Kilometraje</span><b>${x.km?Number(x.km).toLocaleString('es-ES')+' km':'—'}</b></div><div class=recordactions><button onclick="editItv('${x.id}')">Editar</button><button class=dangerbtn onclick="deleteRecord('itv','${x.id}')">Eliminar</button></div></div>`).join('')||'<div class=card>Sin ITV registradas.</div>'}</main>${bottom()}`}
function editItv(id){let x=id?(db.itv||[]).find(r=>r.id===id):null,date=prompt('Fecha ITV (dd/mm/aaaa):',x?.date||todayES());if(date===null)return;if(!pd(date)){alert('Fecha no válida');return}let nextDate=prompt('Próximo vencimiento (dd/mm/aaaa):',x?.nextDate||'');if(nextDate&& !pd(nextDate)){alert('Fecha no válida');return}let result=prompt('Resultado:',x?.result||'Favorable');if(result===null)return;let km=prompt('Kilometraje:',x?.km||'');if(km===null)return;let rec={id:x?.id||('itv_'+Date.now()),vehicle:state.vid,date:date.trim(),nextDate:String(nextDate||'').trim(),result:String(result||'').trim(),km:String(km||'').trim()};if(x)Object.assign(x,rec);else db.itv.push(rec);save();render()}
function taxes(){let rows=(db.taxes||[]).filter(x=>x.vehicle===state.vid).sort((a,b)=>(pd(b.date)||0)-(pd(a.date)||0));app().innerHTML=moduleHead('€ Impuestos')+`<main>${rows.map(x=>`<div class=card><span class=cost>${x.cost!==''&&x.cost!=null?Number(x.cost).toLocaleString('es-ES',{minimumFractionDigits:2})+' €':''}</span><h3>${esc(x.date||'Sin fecha')}</h3><div class=row><span class=muted>Año</span><b>${esc(x.year||'—')}</b></div><div class=row><span class=muted>Municipio</span><b>${esc(x.municipality||'—')}</b></div><div class=recordactions><button onclick="editTax('${x.id}')">Editar</button><button class=dangerbtn onclick="deleteRecord('taxes','${x.id}')">Eliminar</button></div></div>`).join('')||'<div class=card>Sin impuestos registrados.</div>'}</main>${bottom()}`}
function editTax(id){let x=id?(db.taxes||[]).find(r=>r.id===id):null,date=prompt('Fecha de pago (dd/mm/aaaa):',x?.date||todayES());if(date===null)return;if(date&&!pd(date)){alert('Fecha no válida');return}let cost=prompt('Importe (€):',x?.cost??'');if(cost===null)return;let n=String(cost).trim()===''?'':Number(String(cost).replace(',','.'));if(n!==''&&!Number.isFinite(n)){alert('Importe no válido');return}let municipality=prompt('Municipio:',x?.municipality||'');if(municipality===null)return;let rec={id:x?.id||('tax_'+Date.now()),vehicle:state.vid,date:String(date||'').trim(),year:date&&pd(date)?String(pd(date).getFullYear()):String(x?.year||''),cost:n,municipality:String(municipality||'').trim(),status:'Pagado'};if(x)Object.assign(x,rec);else db.taxes.push(rec);save();render()}
function deleteRecord(col,id){if(!confirm('¿Eliminar este registro?'))return;db[col]=db[col].filter(x=>x.id!==id);save();render()}
function docs(){app().innerHTML=moduleHead('▤ Documentos')+`<main><div class=card>Espacio preparado para pólizas, facturas, permiso de circulación y ficha técnica.</div></main>${bottom()}`}
function other(){let rows=(db.other||[]).filter(x=>x.vehicle===state.vid);app().innerHTML=moduleHead('▥ Gastos')+`<main><div class=section>Accesorios y otros</div>${rows.map(x=>`<div class=card><span class=tag>${esc(x.kind||'Gasto')}</span>${x.cost!==''?`<span class=cost>${Number(x.cost).toLocaleString('es-ES',{minimumFractionDigits:2})} €</span>`:''}<h3>${esc(x.description)}</h3><div class=row><span class=muted>Fecha</span><b>${esc(x.date)}</b></div><div class=row><span class=muted>Proveedor</span><b>${esc(x.place||'—')}</b></div>${x.km?`<div class=row><span class=muted>Kilometraje</span><b>${Number(x.km).toLocaleString('es-ES')} km</b></div>`:''}</div>`).join('')||'<div class=card>Sin gastos adicionales registrados.</div>'}</main>${bottom()}`}
function addRecord(){if(state.page==='itv')return editItv(null);if(state.page==='taxes')return editTax(null);alert('Formulario de alta preparado para este módulo en una siguiente mejora.')}
function agenda(){let a=[];db.vehicles.filter(v=>v.status==='Activo'&&v.type!=='Bici').forEach(v=>{let d=itvDue(v);if(d)a.push([d,v,'ITV']);let s=pd(v.insurance?.renewal);if(s)a.push([s,v,'Seguro'])});a.sort((x,y)=>x[0]-y[0]);app().innerHTML=`<div class=top><div class=brand>Agenda</div><div class=sub>Próximos vencimientos</div></div><main>${a.map(x=>`<div class=card onclick="openV('${x[1].id}')"><b>${esc(x[1].alias)} · ${x[2]}</b><span class=cost>${dy(x[0])} días</span><div class=muted>${fd(x[0])}</div></div>`).join('')}</main>${bottom()}`}
function spend(){let sums={};db.workshop.forEach(x=>sums[x.vehicle]=(sums[x.vehicle]||0)+Number(x.cost||0));['glc','smart'].forEach(id=>recurringMaintenanceRecords(id).forEach(x=>sums[id]=(sums[id]||0)+Number(x.cost||0)));db.tires.forEach(x=>sums[x.vehicle]=(sums[x.vehicle]||0)+Number(x.cost||0));(db.taxes||[]).forEach(x=>sums[x.vehicle]=(sums[x.vehicle]||0)+Number(x.cost||0));(db.other||[]).forEach(x=>sums[x.vehicle]=(sums[x.vehicle]||0)+Number(x.cost||0));app().innerHTML=`<div class=top><div class=brand>Gastos</div><div class=sub>Taller, neumáticos, impuestos y otros gastos</div></div><main>${Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([id,n])=>{let v=db.vehicles.find(x=>x.id===id);return `<div class=card><b>${esc(v?.alias||id)}</b><span class=cost>${n.toLocaleString('es-ES',{minimumFractionDigits:2})} €</span></div>`}).join('')}</main>${bottom()}`}
function pending(){
  let items=[];
  db.vehicles.filter(v=>v.status==='Activo').forEach(v=>{
    if(!v.km)items.push([v.id,v.alias,'Kilometraje','Falta indicar el kilometraje actual','km']);
    if(v.type!=='Bici'){
      if(!v.firstRegistration)items.push([v.id,v.alias,'Primera matriculación','Necesaria para calcular correctamente la ITV','firstRegistration']);
      if(!v.plate)items.push([v.id,v.alias,'Matrícula','Dato pendiente','plate']);
      if(!v.insurance?.renewal)items.push([v.id,v.alias,'Seguro','Falta próxima renovación','insurance']);
      if(!latest(db.tires,v.id))items.push([v.id,v.alias,'Neumáticos','Sin datos de neumáticos','tires']);
    }
  });
  app().innerHTML=`<div class=top><button class=back onclick="go('more')">‹ Más</button><div class=brand>Datos pendientes</div><div class=sub>Toca un dato para completarlo</div></div><main>${items.map(x=>`<div class="card pendingcard" onclick="editPending('${x[0]}','${x[4]}')"><b>${esc(x[1])} · ${esc(x[2])}</b><div class=muted>${esc(x[3])}</div><span class=rowchev>›</span></div>`).join('')||'<div class=card>No hay datos pendientes.</div>'}</main>${bottom()}`
}
function more(){app().innerHTML=`<div class=top><div class=brand>Más</div></div><main><div class="card menucard" onclick="go('pending')"><div class=menuicon>!</div><div><b>Datos pendientes</b><p class=muted>Completar información que falta de los vehículos</p></div><span class=chev>›</span></div><div class=card><b>Copias y datos</b><p class=muted>La copia incluye también las fotos. Al importar, Mi Garaje fusiona la información y conserva los datos que ya tengas.</p><button class=add onclick="document.getElementById('importFile').click()">Importar y fusionar copia</button><input id=importFile type=file accept=".json,application/json" hidden onchange="importBackup(this.files[0]);this.value=''"><button class="add secondary" onclick=backup()>Exportar copia completa</button></div></main>${bottom()}`}
function normalizeData(data){
  if(!data||typeof data!=='object')data={};
  for(const k of ['vehicles','workshop','tires','itv','taxes','other','insuranceHistory','insurancePolicies'])if(!Array.isArray(data[k]))data[k]=[];
  // Migrate legacy single-policy records without losing them. Use a stable id so repeated imports do not duplicate policies.
  data.vehicles.forEach(v=>{if(v.type!=='Bici'&&v.insurance&&v.insurance.company&&!data.insurancePolicies.some(p=>p.vehicle===v.id)){data.insurancePolicies.push({id:'legacy_policy_'+v.id,vehicle:v.id,company:v.insurance.company||'',policy:v.insurance.policy||'',holder:v.insurance.holder||'',additional:v.insurance.additional||'',coverage:v.insurance.coverage||'',start:v.insurance.start||'',end:'',bank:v.insurance.bank||'',active:true})}});
  data.vehicles.forEach(v=>v.mileageHistory=Array.isArray(v.mileageHistory)?v.mileageHistory:[]);
  data.schemaVersion=Number(data.schemaVersion)||7;
  return data
}
function useful(v){return !(v===undefined||v===null||v==='')}
function mergeObjects(incoming,local){let out={...(incoming||{})};Object.entries(local||{}).forEach(([k,v])=>{if(useful(v))out[k]=v});return out}
function mergeArray(local,incoming){let m=new Map();(incoming||[]).forEach(x=>m.set(x.id||JSON.stringify(x),x));(local||[]).forEach(x=>{let k=x.id||JSON.stringify(x),prev=m.get(k);m.set(k,prev?mergeObjects(prev,x):x)});return [...m.values()]}
function mergeVehicle(incoming,local){let v=mergeObjects(incoming,local);v.insurance=mergeObjects(incoming?.insurance,local?.insurance);v.photo=local?.photo||incoming?.photo||'';v.mileageHistory=mergeArray(local?.mileageHistory||[],incoming?.mileageHistory||[]);return v}
function mergeData(incoming,local){
  incoming=normalizeData(incoming);local=normalizeData(local);
  let im=new Map(incoming.vehicles.map(v=>[v.id,v])),lm=new Map(local.vehicles.map(v=>[v.id,v])),ids=new Set([...im.keys(),...lm.keys()]);
  let vehicles=[...ids].map(id=>im.has(id)&&lm.has(id)?mergeVehicle(im.get(id),lm.get(id)):(lm.get(id)||im.get(id)));
  return {schemaVersion:Math.max(Number(incoming.schemaVersion)||0,Number(local.schemaVersion)||0,7),
    vehicles,
    workshop:mergeArray(local.workshop,incoming.workshop),
    tires:mergeArray(local.tires,incoming.tires),
    itv:mergeArray(local.itv,incoming.itv),
    taxes:mergeArray(local.taxes,incoming.taxes),
    other:mergeArray(local.other,incoming.other),
    insuranceHistory:mergeArray(local.insuranceHistory,incoming.insuranceHistory),
    insurancePolicies:mergeArray(local.insurancePolicies,incoming.insurancePolicies)
  }
}
function downloadBackup(name){let a=document.createElement('a'),b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),d=new Date(),stamp=d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'_'+String(d.getHours()).padStart(2,'0')+String(d.getMinutes()).padStart(2,'0');a.href=URL.createObjectURL(b);a.download=`Mi_Garaje_${name}_${stamp}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importBackup(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let data=JSON.parse(r.result);if(!data||!Array.isArray(data.vehicles))throw 0;if(!confirm('Se hará primero una copia de seguridad de los datos actuales y después se fusionará el archivo. No se borrarán las fotos ni los datos que ya tengas. ¿Continuar?'))return;downloadBackup('antes_de_importar');let previous=db;db=mergeData(data,db);if(!save()){db=previous;return}alert('Datos fusionados correctamente. Se han conservado los datos y fotos existentes.');state.page='garage';state.filter='Moto';render()}catch(e){console.error(e);alert('No se ha podido importar la copia. El archivo JSON es legible, pero se ha producido un error al fusionar sus datos. Detalle: '+(e?.message||e||'desconocido'))}};r.readAsText(file)}
function backup(){downloadBackup('copia_completa')}
function render(){({garage,vehicle,workshop,tires,insurance,itv,taxes,docs,other,agenda,spend,more,pending}[state.page]||garage)()}render();
